### ISSUE TITLE
orders: use data.identity for peer identity

### ISSUE THREAD

**Issue by caffeinum** [swaponline/sips#3]
## Отделить адрес эфира от идентификатора

Заменить подпись через адрес data.eth на data.identity

Примерно так:
![image](https://user-images.githubusercontent.com/1909384/50167666-ba2b7300-02fa-11e9-8616-6e9dca23f9bf.png)

```javascript
data: {
  identity: { address: '0x1DEN717Y' },
  eth: { address: '0xAbCDeF' },
  btc: { publicKey: '000ffff', address: 'MgMg..' },
}
```

## Зачем?

Чтоб можно было в .eth класть любой адрес, метамаск или внешний кошелек. Это нужно, чтоб избавиться от `destinationSellAddress`, `destinationBuyAddress` в ордере.

**Comment by shendel** [comment]
[+]

**Comment by 7flash** [comment]
Как насчет того, чтобы отправлять эти адреса на сервер репутации, который будет запоминать связь identity с eth/btc? Преимущество в том, что когда пользователь подключает внешний кошелек, он не потеряет репутацию (потому что новый кошелек так же будет связан с identity, как и старый). Недостаток в том, что со стороны это может быть похоже на централизованную регистрацию.
